
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Mar 14 17:29:28 EDT 2025
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A4Symbol {
  /* terminals */
  public static final int TIMES = 2;
  public static final int READ = 12;
  public static final int ELSE = 10;
  public static final int PLUS = 23;
  public static final int DQUOTE = 28;
  public static final int INT = 16;
  public static final int SEMI = 26;
  public static final int END = 7;
  public static final int RETURN = 8;
  public static final int COM = 27;
  public static final int TRUE = 18;
  public static final int IF = 9;
  public static final int WRITE = 11;
  public static final int ID = 14;
  public static final int NUM = 22;
  public static final int EQUALTO = 21;
  public static final int BEGIN = 6;
  public static final int SQUOTE = 29;
  public static final int STRING = 15;
  public static final int EOF = 0;
  public static final int DIVIDE = 3;
  public static final int MAIN = 13;
  public static final int MINUS = 24;
  public static final int FALSE = 19;
  public static final int error = 1;
  public static final int ASSIGN = 25;
  public static final int OPAREN = 4;
  public static final int CPAREN = 5;
  public static final int QSTRING = 30;
  public static final int NULL = 31;
  public static final int REAL = 17;
  public static final int NEQUALTO = 20;
}

